### ISSUE TITLE
You can tap Fire Spirit to infinity :)

### ISSUE THREAD

**Issue by FluffyDiscord** [Sparklmonkey/ElementsTheRevival#3]
Fire Spirit attack can be increased immediately after playing even when player does not have enough fire to do so.

**Comment by Sparklmonkey** [comment]
Thanks for reporting :) I'll look into it and get it fixed

**Comment by Sparklmonkey** [comment]
Thanks again for reporting this. This could be used for pretty much any activated abilty. 
Will be updating the game shortly with the fix :)
